### ISSUE TITLE
gem dependencies seem broken

### ISSUE THREAD

**Issue by gucki** [hmcfletch/encrypted-cookie-store#1]
In my initializer I have:

```
TestLight::Application.config.session_store :encrypted_cookie_store
```

Now I get

```
undefined method `encrypted' for {}:ActionDispatch::Cookies::CookieJar
```

My gemfile.lock contains

```
 * encrypted-cookie-store (0.1)
 * encrypted-cookies (0.2)
```

**Comment by gucki** [comment]
Ok, I got it working. The strange this is if you _only_ add "encrypted-cookie-store" to your gemfile, it does _not_ work.

One has to add both gems (encrypted-cookies, encrypted-cookie-store) to the Gemfile. So it looks some kind of dependency bug in the gemspec.

**Comment by hmcfletch** [comment]
Thanks for opening the issue and commenting on it.  I'll look into it more this week when I get back from vacation.

**Comment by hmcfletch** [comment]
Fixed my dumb requirement bug.  I already had the encrypted-cookies gem in my Gemfile while I was doing the testing for the encrypted-cookie-store.  Pushing version 0.2 to rubygems.
